# Generated by Django 3.2.7 on 2021-10-04 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_posts', '0003_posts_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelTable(
            name='posts',
            table='Posts',
        ),
    ]
